=== ppaulee/MDSim/src/XMLReader/MolSim.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:simpleType name="time">
        <xsd:restriction base="xsd:double"/>
    </xsd:simpleType>

    <xsd:simpleType name="epsilon">
        <xsd:restriction base="xsd:double"/>
    </xsd:simpleType>

    <xsd:simpleType name="sigma">
        <xsd:restriction base="xsd:double"/>
    </xsd:simpleType>

    <xsd:complexType name="dimension">
        <xsd:sequence>
            <xsd:element name="x" type="xsd:int"/>
            <xsd:element name="y" type="xsd:int"/>
            <xsd:element name="z" type="xsd:int"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="point">
        <xsd:sequence>
            <xsd:element name="x" type="xsd:double"/>
            <xsd:element name="y" type="xsd:double"/>
            <xsd:element name="z" type="xsd:double"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="velocity">
        <xsd:sequence>
            <xsd:element name="x" type="xsd:double"/>
            <xsd:element name="y" type="xsd:double"/>
            <xsd:element name="z" type="xsd:double"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="algorithm">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="sv"/>
            <xsd:enumeration value="lj"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="containerAlgorithm">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="naiv"/>
            <xsd:enumeration value="linkedCells"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="simulationContainer">
        <xsd:sequence>
            <xsd:element name="boundaryConditions" type="boundaryConditions"/>
            <xsd:element name="dimension" type="dimension"/>
            <xsd:element name="mesh" type="xsd:double"/>
            <xsd:element name="cutOff" type="xsd:double"/>
            <xsd:element name="containerAlgorithm" type="containerAlgorithm"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="boundaryConditions">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="outflow"/>
            <xsd:enumeration value="reflection"/>
            <xsd:enumeration value="periodic"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="benchmark">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="yes"/>
            <xsd:enumeration value="no"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="Cube">
        <xsd:sequence>
            <xsd:element name="dimension" type ="dimension"/>
            <xsd:element name="startPoint" type ="point"/>
            <xsd:element name="h" type="xsd:double"/>
            <xsd:element name="mass" type="xsd:double"/>
            <xsd:element name="velocity" type="velocity"/>
            <xsd:element name="epsilon" type="epsilon"/>
            <xsd:element name="sigma" type="sigma"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Sphere">
        <xsd:sequence>
            <xsd:element name="center" type ="point"/>
            <xsd:element name="radius" type="xsd:double"/>
            <xsd:element name="h" type="xsd:double"/>
            <xsd:element name="mass" type="xsd:double"/>
            <xsd:element name="velocity" type="velocity"/>
            <xsd:element name="epsilon" type="epsilon"/>
            <xsd:element name="sigma" type="sigma"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="particles">
        <xsd:sequence>
            <xsd:element name="Cube" type="Cube" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="Sphere" type="Sphere" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="thermostats">
        <xsd:sequence>
            <xsd:element name="initialTemperature" type="xsd:double"/>
            <xsd:element name="targetTemperature" type="xsd:double"/>
            <xsd:element name="maxDelta" type="xsd:double"/>
            <xsd:element name="stepSize" type="xsd:int"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="molsim">
        <xsd:sequence>
            <xsd:element name="input_file" type="xsd:string" minOccurs="0"/>
            <xsd:element name="delta_t" type="time"/>
            <xsd:element name="end_time" type="time"/>
            <xsd:element name="output_step" type="xsd:int"/>
            <xsd:element name="epsilon" type="epsilon"/>
            <xsd:element name="sigma" type="sigma"/>
            <xsd:element name="gravity" type="xsd:double"/>
            <xsd:element name="averageV" type ="xsd:double"/>
            <xsd:element name="algorithm" type="algorithm"/>
            <xsd:element name="simulationContainer" type="simulationContainer"/>
            <xsd:element name="particles" type="particles" minOccurs="0"/>
            <xsd:element name="thermostats" type="thermostats" minOccurs="0"/>
            <xsd:element name="benchmark" type="benchmark"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="molsim" type="molsim"/>

</xsd:schema>

=== ppaulee/MDSim/membrane.xml
<?xml version="1.0"?>

<molsim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="src/XMLReader/MolSim.xsd">

    <input_file>../input.txt</input_file>

    <delta_t>0.001</delta_t>

    <end_time>500</end_time>

    <output_step>100</output_step>

    <epsilon>1</epsilon>

    <sigma>1</sigma>

    <gravity>-0.001</gravity>

    <averageV>0</averageV>

    <algorithm>lj</algorithm>

    <simulationContainer>
        <boundaryConditions>
            <xBoundary>1</xBoundary>
            <yBoundary>1</yBoundary>
            <zBoundary>1</zBoundary>
        </boundaryConditions>
        <dimension>
            <x>148</x>
            <y>148</y>
            <z>148</z>
        </dimension>
        <mesh>4</mesh>
        <cutOff>4</cutOff>
        <containerAlgorithm>linkedCells</containerAlgorithm>
    </simulationContainer>

    <particles>
    </particles>

    <thermostats>
        <initialTemperature>80</initialTemperature>
        <targetTemperature>80</targetTemperature>
        <maxDelta>-1</maxDelta>
        <stepSize>1000</stepSize>
    </thermostats>

    <parallelizationStrategy>1</parallelizationStrategy>

    <benchmark>no</benchmark>

</molsim>

=== ppaulee/MDSim/tests/testinput.xml
<?xml version="1.0"?>

<molsim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../src/XMLReader/MolSim.xsd">

    <input_file>../input.txt</input_file>

    <delta_t>1</delta_t>

    <end_time>2</end_time>

    <output_step>3</output_step>

    <epsilon>4</epsilon>

    <sigma>5</sigma>

    <gravity>6</gravity>

    <averageV>7</averageV>

    <algorithm>lj</algorithm>

    <simulationContainer>
        <boundaryConditions>reflection</boundaryConditions>
        <dimension>
            <x>300</x>
            <y>54</y>
            <z>0</z>
        </dimension>
        <mesh>3</mesh>
        <cutOff>3</cutOff>
        <containerAlgorithm>linkedCells</containerAlgorithm>
    </simulationContainer>

    <particles>
        <Cube>
            <dimension>
                <x>250</x>
                <y>20</y>
                <z>1</z>
            </dimension>
            <startPoint>
                <x>0.6</x>
                <y>2</y>
                <z>0</z>
            </startPoint>
            <h>1.2</h>
            <mass>1</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>1.2</epsilon>
            <sigma>1</sigma>
        </Cube>
        <Cube>
            <dimension>
                <x>250</x>
                <y>20</y>
                <z>1</z>
            </dimension>
            <startPoint>
                <x>0.6</x>
                <y>27</y>
                <z>0</z>
            </startPoint>
            <h>1.2</h>
            <mass>2</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>1</epsilon>
            <sigma>1.1</sigma>
        </Cube>
    </particles>
    <thermostats>
        <initialTemperature>40</initialTemperature>
        <targetTemperature>1000</targetTemperature>
        <maxDelta>-1</maxDelta>
        <stepSize>2</stepSize>
    </thermostats>
    <benchmark>yes</benchmark>
</molsim>

=== ppaulee/MDSim/nanoScale.xml
<?xml version="1.0"?>

<molsim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="src/XMLReader/MolSim.xsd">

    <input_file>../input.txt</input_file>

    <delta_t>0.0005</delta_t>

    <end_time>10</end_time>

    <output_step>50</output_step>

    <epsilon>5</epsilon>

    <sigma>1</sigma>

    <gravity>-0.8</gravity>

    <averageV>0.7</averageV>

    <algorithm>lj</algorithm>

    <simulationContainer>
        <boundaryConditions>
            <xBoundary>0</xBoundary>
            <yBoundary>2</yBoundary>
            <zBoundary>2</zBoundary>
        </boundaryConditions>
        <dimension>
            <x>30</x>
            <y>30</y>
            <z>12</z>
        </dimension>
        <mesh>3</mesh>
        <cutOff>3</cutOff>
        <containerAlgorithm>linkedCells</containerAlgorithm>
    </simulationContainer>

    <particles>

        <Cube>
            <dimension>
                <x>20</x>
                <y>25</y>
                <z>10</z>
            </dimension>
            <startPoint>
                <x>6.2</x>
                <y>4</y>
                <z>4</z>
            </startPoint>
            <h>1.2</h>
            <mass>1</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>1</epsilon>
            <sigma>1</sigma>
            <fixed>false</fixed>
        </Cube>
        <Cube>
            <dimension>
                <x>2</x>
                <y>30</y>
                <z>12</z>
            </dimension>
            <startPoint>
                <x>4</x>
                <y>4</y>
                <z>4</z>
            </startPoint>
            <h>1</h>
            <mass>1</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>2</epsilon>
            <sigma>1.1</sigma>
            <fixed>true</fixed>
        </Cube>
        <Cube>
            <dimension>
                <x>2</x>
                <y>30</y>
                <z>12</z>
            </dimension>
            <startPoint>
                <x>30.2</x>
                <y>4</y>
                <z>4</z>
            </startPoint>
            <h>1</h>
            <mass>1</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>2</epsilon>
            <sigma>1.1</sigma>
            <fixed>true</fixed>
        </Cube>
    </particles>

    <thermostats>
        <initialTemperature>40</initialTemperature>
        <targetTemperature>10</targetTemperature>
        <maxDelta>-1</maxDelta>
        <stepSize>1000</stepSize>
    </thermostats>

    <parallelizationStrategy>1</parallelizationStrategy>

    <simulationType>simuFlow</simulationType>

    <benchmark>no</benchmark>

</molsim>

=== ppaulee/MDSim/molsim.xml
<?xml version="1.0"?>

<molsim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="src/XMLReader/MolSim.xsd">

    <input_file>../input.txt</input_file>

    <delta_t>0.014</delta_t>

    <end_time>1000</end_time>

    <output_step>100</output_step>

    <epsilon>5</epsilon>

    <sigma>1</sigma>

    <gravity>10</gravity>

    <averageV>0.1</averageV>

    <algorithm>lj</algorithm>

    <simulationContainer containerAlgorithm="linkedCells">
        <boundaryConditions>reflection</boundaryConditions>
        <dimension>
            <x>300</x>
            <y>300</y>
            <z>300</z>
        </dimension>
        <mesh>3</mesh>
        <cutOff>3</cutOff>
    </simulationContainer>

    <particles>
        <Cube>
            <dimension>
                <x>50</x>
                <y>14</y>
                <z>1</z>
            </dimension>
            <startPoint>
                <x>0.6</x>
                <y>2</y>
                <z>0</z>
            </startPoint>
            <h>1.2</h>
            <mass>1</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>1</epsilon>
            <sigma>1</sigma>
        </Cube>
        <Cube>
            <dimension>
                <x>50</x>
                <y>14</y>
                <z>1</z>
            </dimension>
            <startPoint>
                <x>0.6</x>
                <y>19</y>
                <z>0</z>
            </startPoint>
            <h>1.2</h>
            <mass>2</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>1</epsilon>
            <sigma>0.9412</sigma>
        </Cube>
    </particles>

    <benchmark>yes</benchmark>

</molsim>

=== ppaulee/MDSim/3DRayleigh-Taylor.xml
<?xml version="1.0"?>

<molsim xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="src/XMLReader/MolSim.xsd">

    <input_file>../input.txt</input_file>

    <delta_t>0.0005</delta_t>

    <end_time>100</end_time>

    <output_step>100</output_step>

    <epsilon>1</epsilon>

    <sigma>1.2</sigma>

    <gravity>-12.44</gravity>

    <averageV>6.3245</averageV>

    <algorithm>lj</algorithm>

    <simulationContainer>
        <boundaryConditions>
            <xBoundary>2</xBoundary>
            <yBoundary>1</yBoundary>
            <zBoundary>0</zBoundary>
        </boundaryConditions>
        <dimension>
            <x>60</x>
            <y>60</y>
            <z>60</z>
        </dimension>
        <mesh>2.5</mesh>
        <cutOff>2.5</cutOff>
        <containerAlgorithm>linkedCells</containerAlgorithm>
    </simulationContainer>

    <particles>
        <Cube>
            <dimension>
                <x>50</x>
                <y>20</y>
                <z>50</z>
            </dimension>
            <startPoint>
                <x>6.2</x>
                <y>4.2</y>
                <z>6.2</z>
            </startPoint>
            <h>1.2</h>
            <mass>1</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>1</epsilon>
            <sigma>1.2</sigma>
            <fixed>false</fixed>
        </Cube>
        <Cube>
            <dimension>
                <x>50</x>
                <y>20</y>
                <z>50</z>
            </dimension>
            <startPoint>
                <x>6.2</x>
                <y>32</y>
                <z>6.2</z>
            </startPoint>
            <h>1.2</h>
            <mass>2</mass>
            <velocity>
                <x>0</x>
                <y>0</y>
                <z>0</z>
            </velocity>
            <epsilon>1</epsilon>
            <sigma>1.1</sigma>
            <fixed>false</fixed>
        </Cube>
    </particles>

    <thermostats>
        <initialTemperature>0.5</initialTemperature>
        <targetTemperature>0.5</targetTemperature>
        <maxDelta>-1</maxDelta>
        <stepSize>1000</stepSize>
    </thermostats>

    <parallelizationStrategy>1</parallelizationStrategy>

    <benchmark>no</benchmark>

</molsim>
